### PR TITLE
Livesync without platform syncs all devices

### PR DESCRIPTION
**Pull request by tzraikov**

### CODE REVIEW

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by tzraikov** [comment]
run ci

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by rosen-vladimirov** [comment]
:+1:

**Pull request merged**
