### PR TITLE
SysInfo uses android and adb paths from parameter

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
As different CLIs have different requirements for paths to android and adb executable,
make sure SysInfo checks them from correct executable paths.

### CODE REVIEW

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by teobugslayer** [comment]
:-1:

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by Mitko-Kerezov** [comment]
:+1: for the new commit, I quite prefer the new way of checking for `android` to the old one, good work!

**Pull request merged**
