### PR TITLE
Move logic for getting Xcode version to xcode-select-service

### PR DESCRIPTION
**Pull request by Mitko-Kerezov**
The logic is now used more than once and has to be extracted to a common place. Add test
Re-targeted from https://github.com/telerik/mobile-cli-lib/pull/644
Ping @rosen-vladimirov

### CODE REVIEW

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by rosen-vladimirov** [comment]
:+1:

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by justcodebuilduser** [comment]
:heart:

**Pull request merged**
