### PR TITLE
Share Progress indicator between the CLIs

### PR DESCRIPTION
**Pull request by teobugslayer**
See https://github.com/NativeScript/nativescript-cli/issues/1294

### CODE REVIEW

**Comment by Mitko-Kerezov** [comment]
:+1:

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by rosen-vladimirov** [comment]
/home/ubuntu/jenkins/workspace/ICE_mobile-cli-lib_PR/progress-indicator.ts(4,43): error TS2304: Cannot find name 'IProgressIndicator'.

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by rosen-vladimirov** [comment]
:+1:

**Pull request merged**
