### PR TITLE
Use a temporary copy of built-in adb

### PR DESCRIPTION
**Pull request by teobugslayer**
Required for https://github.com/NativeScript/nativescript-cli/issues/1247

### CODE REVIEW

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by teobugslayer** [comment]
Tested on Mac & Windows for the AB CLI and Proton/Win

**Comment by rosen-vladimirov** [comment]
The following warnings are shown in the output of `appbuilder-cli`:
```
cp: dest file already exists: /tmp/telerik-common-lib-0.1.1/NOTICE.txt
cp: dest file already exists: /tmp/telerik-common-lib-0.1.1/NOTICE.txt
cp: dest file already exists: /tmp/telerik-common-lib-0.1.1/adb
```
We should set `shelljs.config.silent` to true or you should pass `{silent: true}` as options of current copying of adb files.

**Comment by teobugslayer** [comment]
Will create a separate PR against the AB CLI.

**Pull request merged**
