### PR TITLE
Add the mkdir definition to shelljs.d.ts

### PR DESCRIPTION
**Pull request by hdeshev**
A minor d.ts change needed by the [NPM scope PR](https://github.com/NativeScript/nativescript-cli/pull/1068)

### CODE REVIEW

**Comment by teobugslayer** [comment]
:+1:

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by justcodebuilduser** [comment]
:heart:

**Pull request merged**
