### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
Update README.md

### CODE REVIEW

**Comment by justcodebuilduser** [comment]
:smile_cat:

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by justcodebuilduser** [comment]
:smile_cat:

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by justcodebuilduser** [comment]
:smile_cat:

**Comment by rosen-vladimirov** [comment]
run ci

**Pull request closed without merging**
