### PR TITLE
Add isTablet property for deviceInfo

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
For each device we can add isTablet property that will be true when we detect the device is Tablet.
Could be used to show different images in the UI.

### CODE REVIEW

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by Mitko-Kerezov** [comment]
:+1: - looks cool

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by justcodebuilduser** [comment]
:heart:

**Pull request merged**
