### PR TITLE
Added getLsStats method in file-system which calls lstat

### PR DESCRIPTION
**Pull request by tzraikov**

### CODE REVIEW

**Comment by tzraikov** [comment]
run ci

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by tzraikov** [comment]
run ci

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by justcodebuilduser** [comment]
:heart:

**Pull request merged**
