### PR TITLE
Add analytics for Sublime

### PR DESCRIPTION
**Pull request by TsvetanMilanov**
We need to redirect the analytics data sent from Sublime to separate analytics project so we can keep track of how many users are using Telerik AppBuilder for Sublime Text.

### CODE REVIEW

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by rosen-vladimirov** [comment]
:+1:

**Comment by justcodebuilduser** [comment]
:heart:

**Pull request merged**
