### PR TITLE
Integrate livesync logic from android runtime

### PR DESCRIPTION
**Pull request by Fatme**
https://github.com/NativeScript/nativescript-cli/issues/742

### CODE REVIEW

**Comment by teobugslayer** [comment]
Why do we need this PR? Can we get a link to the issue resolved?

**Comment by rosen-vladimirov** [comment]
I believe this is to fix issues with some Android devices which have "intersting" logic of permissions when starting the app (not compatible with other Android devices). For example this one https://github.com/NativeScript/nativescript-cli/issues/732 will be fixed with these changes

**Comment by Fatme** [comment]
Here is the issue - https://github.com/NativeScript/nativescript-cli/issues/742

**Comment by teobugslayer** [comment]
:+1:

**Pull request merged**
