### PR TITLE
Fixed: getRunningSimulator is slow, so we should call it only when th…

### PR DESCRIPTION
**Pull request by tzraikov**
Fixed: getRunningSimulator is slow and causes LiveSync to wait for about 10 seconds, so we should call it only when there is a simulator process running

ping @rosen-vladimirov , @TsvetanMilanov

### CODE REVIEW

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by tzraikov** [comment]
run ci

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by tzraikov** [comment]
run ci

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by tzraikov** [comment]
run ci

**Comment by justcodebuilduser** [comment]
:broken_heart:

**Comment by justcodebuilduser** [comment]
:heart:

**Pull request merged**
