### PR TITLE
Fixed: livesync not working for iOS devices

### PR DESCRIPTION
**Pull request by tzraikov**
ios-devices-file-system service can't create directories on ios devices after removing async methods in CLI.

### CODE REVIEW

**Comment by justcodebuilduser** [comment]
:heart:

**Comment by KristinaKoeva** [comment]
Would you please change your commit message and PR description to something that describes what the problem was and how you fixed it. It is really hard for all of us that are not familiar with the code to instantly understand the problem and the resolution :)
https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines

**Comment by tzraikov** [comment]
@KristinaKoeva Is it now better?

**Comment by KristinaKoeva** [comment]
It's great, thank you !

**Comment by rosen-vladimirov** [comment]
Closing this as the change has been applied in another PR: https://github.com/telerik/mobile-cli-lib/pull/860

**Pull request closed without merging**
